#!/bin/bash
# http://go2linux.garron.me/mysql-backup-mysqldump/
# https://stackoverflow.com/questions/18870244/can-i-have-multiple-mysqldump-sections-in-my-cnf

EPOCH=`date +%s`
sudo mysqldump --defaults-file="/home/vagrant/.my.cnf.backup" -v -u backup -p moodle | sudo gzip -v > moodle-db-backup-$EPOCH.dump.gz
